import './Welcome/Welcome.stories';
import './TextInput/TextInput.stories';
import './Icons/Icon.stories'
import './Heading/Heading.stories'
import "./Image/Image.stories"
import "./Button/Button.stories"
import "./Carousel/DSCarousel.stories"
import "./PricingCard/PricingCard.stories"
import "./SelectInput/SelectInput.stories"
import "./Hr/Hr.stories"
import "./P/P.stories"
import "./Modal/Modal.stories"
import "./Slider/Slider.stories"
import "./Upload/Upload.stories"